image:
  # -- Image pull policy.
  pullPolicy: IfNotPresent
  # -- Image repository.
  repository: registry.k8s.io/kwok/kwok
  # -- Overrides the image tag whose default is {{ .Chart.AppVersion }}.
  tag: ""

# -- Image pull secrets.
imagePullSecrets: []

# -- Override the `name` of the chart.
nameOverride: ""

# -- Override the `fullname` of the chart.
fullnameOverride: "kwok-controller"

podSecurityContext: {}
securityContext: {}

nodeSelector: {}
resources: {}
affinity: {}

# -- The replica count for Deployment.
replicas: 1

# -- Change `hostNetwork` to `true` if you want to deploy in a kind cluster.
hostNetwork: false
tolerations:
- operator: Exists
  effect: NoSchedule
  key: node-role.kubernetes.io/control-plane
- operator: Exists
  effect: NoSchedule
  key: node-role.kubernetes.io/master
volumes: []
env:
- name: POD_IP
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
- name: HOST_IP
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
volumeMounts: []
enableDeployment: true
