apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: {{ include "kwok.fullname" . }}
  labels:
    {{- include "kwok.labels" . | nindent 4 }}
spec:
  priorityLevelConfiguration:
    name: exempt
  matchingPrecedence: 1000
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: {{ include "kwok.fullname" . }}
        namespace: {{ .Release.Namespace }}
