---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kwok.fullname" . }}
  labels:
    {{- include "kwok.labels" . | nindent 4 }}
data:
  kwok.yaml: |-
    {{- $.Files.Get "conf/kwok.yaml" | nindent 4 }}
