apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- ../crd
- ../rbac
- service.yaml
- deployment.yaml

configMapGenerator:
- name: kwok
  namespace: kube-system
  options:
    disableNameSuffixHash: true
  files:
  - kwok.yaml

labels:
- includeSelectors: true
  pairs:
    app: kwok-controller
