name: Test Site

on:
  pull_request:
    paths:
    - site/**/*
    - demo/**/*
    - .github/workflows/test-site.yaml
  push:
    paths:
    - site/**/*
    - demo/**/*
    - .github/workflows/test-site.yaml

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check site
      shell: bash
      run: |
        make -C site check
