apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: default
spec:
  containers:
  - name: fake-container
    image: fake-image
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 1200m
      limits:
        cpu: 1500m
  tolerations:
  - key: "kwok.x-k8s.io/node"
    operator: "Exists"
    effect: "NoSchedule"
